=== PabloOB19/DatabaseClinic/Database/XmlFiles/DataDTD.dtd
<!ELEMENT DataBase (patient*, doctor*, appointment*, surgery*, equipment*, role*, user*)>

<!ELEMENT patient ANY>
<!ATTLIST patient id CDATA #IMPLIED>

<!ELEMENT doctor ANY>
<!ATTLIST doctor id CDATA #IMPLIED>

<!ELEMENT appointment ANY>
<!ATTLIST appointment id CDATA #IMPLIED>

<!ELEMENT surgery ANY>
<!ATTLIST surgery id CDATA #IMPLIED>

<!ELEMENT equipment ANY>
<!ATTLIST equipment id CDATA #IMPLIED>

<!ELEMENT role ANY>
<!ATTLIST role roleId CDATA #IMPLIED>

<!ELEMENT user ANY>
<!ATTLIST user userId CDATA #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT turn (#PCDATA)>
<!ELEMENT specialty (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT expiration_date (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== PabloOB19/DatabaseClinic/Database/XmlFiles/DataXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DataBase SYSTEM "DataDTD.dtd">
<DataBase>
    <patient id="1">
        <name>Laura</name>
        <surname>Garcia</surname>
        <email>lauragar@gmail.com</email>
        <sex>FEMALE</sex>
        <dob>2000-01-25</dob>
        <height>160</height>
        <weight>55.0</weight>
        <info>is celiac and lactose intolerant</info>
    </patient>
    <patient id="2">
        <name>Alejandro</name>
        <surname>Ramirez</surname>
        <email>a.ramirez@gmail.com</email>
        <sex>FEMALE</sex>
        <dob>1999-02-04</dob>
        <height>190</height>
        <weight>81.0</weight>
        <info>nothing relevant</info>
    </patient>
    <patient id="3">
        <name>Pablo</name>
        <surname>Lopez</surname>
        <email>pablolopez@gmail.com</email>
        <sex>MALE</sex>
        <dob>1980-01-23</dob>
        <height>170</height>
        <weight>70.0</weight>
        <info>Has sensitive skin</info>
    </patient>
    <doctor id="1">
        <name>Ana</name>
        <surname>Sanmartín</surname>
        <email>ana.sanmartin@gmail.com</email>
        <sex>FEMALE</sex>
        <dob>1997-01-10</dob>
        <specialty>Anti-Aging Dermatology</specialty>
    </doctor>
    <doctor id="2">
        <name>Raul</name>
        <surname>García</surname>
        <email>raulprr@gmail.com</email>
        <sex>MALE</sex>
        <dob>1965-10-10</dob>
        <specialty>Body Aesthetic</specialty>
    </doctor>
    <doctor id="3">
        <name>Gianluca</name>
        <surname>Cornetta</surname>
        <email>gianlu@gmail.com</email>
        <sex>MALE</sex>
        <dob>1980-10-10</dob>
        <specialty>Endocrinology</specialty>
    </doctor>
    <doctor id="4">
        <name>Eloy</name>
        <surname>Raya</surname>
        <email>eloyraya@gmail.com</email>
        <sex>MALE</sex>
        <dob>1965-09-09</dob>
        <specialty>Body Aesthetic</specialty>
    </doctor>
    <appointment id="1">
        <type>GENERAL_CHECKUP</type>
        <date>2026-10-10</date>
        <price>150.0</price>
        <turn>EARLY_MORNING</turn>
    </appointment>
    <appointment id="2">
        <type>SPECIALIST_VISIT</type>
        <date>2026-11-25</date>
        <price>250.0</price>
        <turn>LATE_MORNING</turn>
    </appointment>
    <appointment id="3">
        <type>FOLLOW_UP</type>
        <date>2027-01-10</date>
        <price>250.0</price>
        <turn>EARLY_MORNING</turn>
    </appointment>
    <appointment id="4">
        <type>FOLLOW_UP</type>
        <date>2027-04-04</date>
        <price>250.0</price>
        <turn>EARLY_AFTERNOON</turn>
    </appointment>
    <surgery id="1">
        <type>LIPOSUCTION</type>
        <date>2026-10-15</date>
        <price>7000.0</price>
        <turn>EARLY_MORNING</turn>
    </surgery>
    <surgery id="2">
        <type>ABDOMINOPLASTY</type>
        <date>2026-09-09</date>
        <price>8000.0</price>
        <turn>LATE_MORNING</turn>
    </surgery>
    <equipment id="1">
        <name>Scalpel</name>
        <category>INSTRUMENT</category>
        <quantity>10</quantity>
        <price>25.5</price>
        <expiration_date>2030-12-31</expiration_date>
    </equipment>
    <equipment id="2">
        <name>Surgical scissors</name>
        <category>INSTRUMENT</category>
        <quantity>15</quantity>
        <price>18.75</price>
        <expiration_date>2030-12-31</expiration_date>
    </equipment>
    <equipment id="3">
        <name>X-ray machine</name>
        <category>MACHINE</category>
        <quantity>1</quantity>
        <price>12000.0</price>
        <expiration_date>2032-01-01</expiration_date>
    </equipment>
    <equipment id="4">
        <name>Bandages</name>
        <category>SUPPLY</category>
        <quantity>100</quantity>
        <price>5.75</price>
        <expiration_date>2028-07-20</expiration_date>
    </equipment>
    <equipment id="5">
        <name>Bandages</name>
        <category>MACHINE</category>
        <quantity>34</quantity>
        <price>89.0</price>
        <expiration_date>2030-07-14</expiration_date>
    </equipment>
    <equipment id="6">
        <name>MRI</name>
        <category>MACHINE</category>
        <quantity>1</quantity>
        <price>20000.0</price>
        <expiration_date>2050-01-01</expiration_date>
    </equipment>
    <role roleId="1">
        <name>Admin</name>
    </role>
    <role roleId="2">
        <name>Doctor</name>
    </role>
    <role roleId="3">
        <name>Patient</name>
    </role>
    <role roleId="5">
        <name>Receptionist</name>
    </role>
    <user userId="14">
        <username>m</username>
        <email>m@m.com</email>
    </user>
    <user userId="28">
        <username>raulprr</username>
        <email>raulprr@gmail.com</email>
    </user>
    <user userId="29">
        <username>laugarcia</username>
        <email>lauragar@gmail.com</email>
    </user>
    <user userId="30">
        <username>p</username>
        <email>p@gmai.com</email>
    </user>
</DataBase>
